"""Ajout IP aux actions

Revision ID: 0550bb4083f7
Revises: 363c7cedd3bd
Create Date: 2017-05-07 15:44:54.302010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0550bb4083f7'
down_revision = '363c7cedd3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('ip', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'ip')
    # ### end Alembic commands ###
