"""Migration users

Revision ID: 0f6485160e01
Revises: f7f34ea0f9c3
Create Date: 2017-05-20 11:50:46.126613

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6485160e01'
down_revision = 'f7f34ea0f9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('abo_rc', sa.Boolean(), nullable=True),
    sa.Column('abo_membres', sa.Boolean(), nullable=True),
    sa.Column('abo_irfm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actions', 'users', ['user_id'], ['id'])

    op.execute("""
        INSERT INTO users(nick, email, admin, abo_rc, abo_membres, abo_irfm)
        SELECT DISTINCT
            nick, email,
            CASE WHEN nick = '!rc' THEN true ELSE false END,
            false, false, false
        FROM actions
        WHERE nick != '';
    """)

    op.execute("""
        UPDATE actions a
        SET user_id = (SELECT u.id
                       FROM users u
                       WHERE u.nick = a.nick AND u.email = a.email)
        WHERE a.nick != '';
    """)

    # op.drop_column('actions', 'email')
    # op.drop_column('actions', 'nick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('nick', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
