"""Ajout nom complet parlementaire

Revision ID: 2267f3efb8fa
Revises: f7b6ff041b6f
Create Date: 2017-05-06 16:10:09.041141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2267f3efb8fa'
down_revision = 'f7b6ff041b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parlementaires', sa.Column('nom_complet', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parlementaires', 'nom_complet')
    # ### end Alembic commands ###
