"""Ajout emails et twitter aux parlementaires

Revision ID: 2cbf8b8a98b2
Revises: 33e04063a022
Create Date: 2017-05-14 18:00:52.089982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbf8b8a98b2'
down_revision = '33e04063a022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parlementaires', sa.Column('emails', sa.Unicode(), nullable=True))
    op.add_column('parlementaires', sa.Column('twitter', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parlementaires', 'twitter')
    op.drop_column('parlementaires', 'emails')
    # ### end Alembic commands ###
