"""Ajout icone etape

Revision ID: 33e04063a022
Revises: 0bb141c3f068
Create Date: 2017-05-10 20:17:52.083429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e04063a022'
down_revision = '0bb141c3f068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etapes', sa.Column('icone', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etapes', 'icone')
    # ### end Alembic commands ###
