"""Ajout actions

Revision ID: 363c7cedd3bd
Revises: 2267f3efb8fa
Create Date: 2017-05-07 12:26:54.579934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363c7cedd3bd'
down_revision = '2267f3efb8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('nick', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('attachment', sa.Unicode(), nullable=True),
    sa.Column('etape_id', sa.Integer(), nullable=True),
    sa.Column('parlementaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etape_id'], ['etapes.id'], ),
    sa.ForeignKeyConstraint(['parlementaire_id'], ['parlementaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    # ### end Alembic commands ###
