"""Ajout abonnements

Revision ID: 56431e581030
Revises: 0f6485160e01
Create Date: 2017-05-20 19:37:03.948322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56431e581030'
down_revision = '0f6485160e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parlementaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parlementaire_id'], ['parlementaires.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('actions', 'email')
    op.drop_column('actions', 'nick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('nick', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('abonnements')
    # ### end Alembic commands ###
