"""Initialisation

Revision ID: 8d32ba048444
Revises: 
Create Date: 2017-05-05 23:06:35.469060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d32ba048444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parlementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Unicode(), nullable=True),
    sa.Column('prenom', sa.Unicode(), nullable=True),
    sa.Column('sexe', sa.Enum('H', 'F', name='sexes'), nullable=True),
    sa.Column('adresse', sa.Unicode(), nullable=True),
    sa.Column('chambre', sa.Enum('SEN', 'AN', name='chambres'), nullable=True),
    sa.Column('mandat_debut', sa.DateTime(), nullable=True),
    sa.Column('mandat_fin', sa.DateTime(), nullable=True),
    sa.Column('num_deptmt', sa.Unicode(), nullable=True),
    sa.Column('nom_circo', sa.Unicode(), nullable=True),
    sa.Column('num_circo', sa.Integer(), nullable=True),
    sa.Column('groupe', sa.Unicode(), nullable=True),
    sa.Column('groupe_sigle', sa.Unicode(), nullable=True),
    sa.Column('url_photo', sa.Unicode(), nullable=True),
    sa.Column('url_rc', sa.Unicode(), nullable=True),
    sa.Column('url_off', sa.Unicode(), nullable=True),
    sa.Column('etape', sa.Enum('NOUVEAU', name='etapes'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parlementaires')
    # ### end Alembic commands ###
