"""Suppression groupe

Revision ID: 9784b9baaf7d
Revises: 8d32ba048444
Create Date: 2017-05-06 00:06:25.565160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9784b9baaf7d'
down_revision = '8d32ba048444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parlementaires', 'groupe')
    op.drop_column('parlementaires', 'groupe_sigle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parlementaires', sa.Column('groupe_sigle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parlementaires', sa.Column('groupe', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
