"""Suppression modele étape

Revision ID: a228d37e99e9
Revises: 56431e581030
Create Date: 2017-05-21 11:19:36.750227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a228d37e99e9'
down_revision = '56431e581030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('etape', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE actions a
        SET etape = (SELECT ordre FROM etapes e WHERE e.id = a.etape_id);
    """)

    op.drop_constraint('actions_etape_id_fkey', 'actions', type_='foreignkey')
    op.drop_column('actions', 'etape_id')

    op.add_column('parlementaires', sa.Column('etape', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE parlementaires p
        SET etape = (SELECT ordre FROM etapes e WHERE e.id = p.etape_id);
    """)

    op.drop_constraint('parlementaires_etape_id_fkey', 'parlementaires', type_='foreignkey')
    op.drop_column('parlementaires', 'etape_id')

    op.drop_table('etapes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ordre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('couleur', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='etapes_pkey')
    )
    op.add_column('parlementaires', sa.Column('etape_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parlementaires_etape_id_fkey', 'parlementaires', 'etapes', ['etape_id'], ['id'])
    op.drop_column('parlementaires', 'etape')
    op.add_column('actions', sa.Column('etape_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('actions_etape_id_fkey', 'actions', 'etapes', ['etape_id'], ['id'])
    op.drop_column('actions', 'etape')
    # ### end Alembic commands ###
