"""Ajout entité groupe + relation parl

Revision ID: beb25e23d267
Revises: 9784b9baaf7d
Create Date: 2017-05-06 00:07:59.939030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'beb25e23d267'
down_revision = '9784b9baaf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigle', sa.Unicode(), nullable=True),
    sa.Column('nom', sa.Unicode(), nullable=True),
    sa.Column('chambre', ENUM('SEN', 'AN', name='chambres', create_type=False), nullable=True),
    sa.Column('couleur', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parlementaires', sa.Column('groupe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parlementaires', 'groupes', ['groupe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parlementaires', type_='foreignkey')
    op.drop_column('parlementaires', 'groupe_id')
    op.drop_table('groupes')
    # ### end Alembic commands ###
