"""init

Revision ID: f7b6ff041b6f
Revises: 
Create Date: 2017-05-06 11:00:23.580421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b6ff041b6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('couleur', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigle', sa.Unicode(), nullable=True),
    sa.Column('nom', sa.Unicode(), nullable=True),
    sa.Column('chambre', sa.Enum('AN', 'SEN', name='chambres'), nullable=True),
    sa.Column('couleur', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parlementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.Unicode(), nullable=True),
    sa.Column('prenom', sa.Unicode(), nullable=True),
    sa.Column('sexe', sa.Enum('F', 'H', name='sexes'), nullable=True),
    sa.Column('adresse', sa.Unicode(), nullable=True),
    sa.Column('chambre', sa.Enum('AN', 'SEN', name='chambres'), nullable=True),
    sa.Column('mandat_debut', sa.DateTime(), nullable=True),
    sa.Column('mandat_fin', sa.DateTime(), nullable=True),
    sa.Column('num_deptmt', sa.Unicode(), nullable=True),
    sa.Column('nom_circo', sa.Unicode(), nullable=True),
    sa.Column('num_circo', sa.Integer(), nullable=True),
    sa.Column('groupe_id', sa.Integer(), nullable=True),
    sa.Column('url_photo', sa.Unicode(), nullable=True),
    sa.Column('url_rc', sa.Unicode(), nullable=True),
    sa.Column('url_off', sa.Unicode(), nullable=True),
    sa.Column('etape_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['etape_id'], ['etapes.id'], ),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parlementaires')
    op.drop_table('groupes')
    op.drop_table('etapes')
    # ### end Alembic commands ###
