"""Ajout champ mails envoyes

Revision ID: f7f34ea0f9c3
Revises: 2cbf8b8a98b2
Create Date: 2017-05-14 20:12:58.541498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f34ea0f9c3'
down_revision = '2cbf8b8a98b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parlementaires', sa.Column('mails_envoyes', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parlementaires', 'mails_envoyes')
    # ### end Alembic commands ###
